version: 2
jobs:
  build-go1.11:
    docker:
        - image: golang:1.11
    working_directory: /go/src/github.com/kolide/updater
    steps: &steps
      - checkout
      - run: GO111MODULE=on go mod download
      - run: GO111MODULE=on go test -race -cover -v $(go list ./... | grep -v /vendor/)

workflows:
  version: 2
  build:
    jobs:
      - build-go1.11
